;
; File generated by cc65 v 2.16 - Git N/A
;
	.fopt		compiler,"cc65 v 2.16 - Git N/A"
	.setcpu		"6502X"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_start
	.import		_muovi_sprites_esempio
	.export		_conta
	.export		_main

.segment	"BSS"

_conta:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; start();
;
	jsr     _start
;
; while(1) {
;
	jmp     L000E
;
; conta=conta+1;
;
L0008:	lda     _conta
	ldx     _conta+1
	jsr     incax1
	sta     _conta
	stx     _conta+1
;
; if (conta==50) {
;
	lda     _conta
	ldx     _conta+1
	cpx     #$00
	bne     L0010
	cmp     #$32
L0010:	jsr     booleq
	jeq     L000E
;
; muovi_sprites_esempio();
;
	jsr     _muovi_sprites_esempio
;
; conta = 0;
;
	ldx     #$00
	lda     #$00
	sta     _conta
	stx     _conta+1
;
; while(1) {
;
L000E:	jmp     L0008
;
; }
;
	rts

.endproc

